version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - mysql
    secrets:
      - db_password
    volumes:
      - fpm_sock:/run/php/
      - web_data:/var/www/html

  php:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/usr/sbin/php-fpm8.1", "-F", "-c", "/etc/php/8.1/fpm/"]
    environment:
      APP_KEY: "base64:fh/LQsJyMwPYX/wUtAH3pZiCd+j57hyDMZslBcqic4U="
      APP_URL: "http://example.com:8080"
      DB_HOST: docker-bookstack_mysql_1
      DB_DATABASE: bookstack
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - mysql
    secrets:
      - db_password
    volumes:
      - fpm_sock:/run/php/

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bookstack
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
secrets:
  db_password:
    file: .env
volumes:
  mysql_data:
  fpm_sock:
  web_data:
