apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  labels:
    app.kubernetes.io/name: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bookstack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bookstack
    spec:
      containers:
      - name: nginx
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/bookstack/prod/nginx:stable
        imagePullPolicy: Always
        command: ["nginx", "-g", "daemon off;"]
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 8080
          name: bookstack-web
        volumeMounts:
        - name: fpm-sock
          mountPath: /run/php
      - name: php
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/bookstack/prod/php:stable
        imagePullPolicy: Always
        command: ["/usr/sbin/php-fpm8.1", "-F", "-c", "/etc/php/8.1/fpm/"]
        env:
          - name: APP_KEY
            valueFrom:
              configMapKeyRef:
                name: bookstack
                key: app_key
          - name: APP_URL
            valueFrom:
              configMapKeyRef:
                name: bookstack
                key: app_url
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: bookstack
                key: db_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: bookstack
                key: db_database
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: bookstack
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: bookstack
                key: db_password
        livenessProbe:
          exec:
            command:
            - /bin/true
        volumeMounts:
        - name: fpm-sock
          mountPath: /run/php
      volumes:
      - name: fpm-sock
        emptyDir:
          sizeLimit: 10Mi
