apiVersion: v1
kind: Service
metadata:
  name: bookstack
  labels:
    app.kubernetes.io/name: bookstack
spec:
  selector:
    app.kubernetes.io/name: bookstack
  ports:
    - protocol: TCP
      port: 80
      targetPort: bookstack-web
  type: LoadBalancer
